# Generated by Django 5.1.2 on 2026-09-11 01:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO-like, p. ej. EUR, ARS, USD.', max_length=8, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('value_in_usd', models.DecimalField(decimal_places=6, help_text='Cuántos dólares estadounidenses (USD) vale 1 unidad de esta divisa.', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Carga de saldo'), ('buy', 'Compra de divisa'), ('withdraw', 'Retiro de divisa')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='core.currency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core.wallet')),
            ],
            options={
                'ordering': ['currency__code'],
                'constraints': [models.UniqueConstraint(fields=('wallet', 'currency'), name='unique_wallet_currency')],
            },
        ),
    ]
